### ISSUE TITLE
vectors_klee_bug.x86_64 may have unreachable asserts

### ISSUE THREAD

**Issue by delcypher** [delcypher/fp-benchmarks-imperial#14]
The `vectors_klee_bug.x86_64` benchmark declares several counter example locations in its spec. However when I run our tool on it some of those are not covered and our exploration appears to be exhaustive. Later on this results in a warning when analysing our results.

```
WARNING:MainThread: MATCH SPEC for task no_assert_fail but with warnings:
/home/user/build_O2/benchmarks/c/imperial/gsl/benchmarks/vectors_klee_bug.x86_64.bc (/home/imperial/experiments/imperial/tool_exchange/0/wd/workdir-57/klee-wd)
Observed counter examples do not cover all listed for this task in spec. The following locations were not covered:
{'vector_example.c': {57, 58}}
```

I suspect those locations (i.e. lines `57` and `58` in `vector_example.c`) are not reachable? @ccadar could you look into this and fix if appropriate.

**Comment by ccadar** [comment]
Hi @delcypher , I didn't write the spec file.  But it looks fine to me, except that I don't understand why `KLEE` is not defined when `BUG` is.   I think that's the problem.

**Comment by delcypher** [comment]
> Hi @delcypher , I didn't write the spec file. 

@afd did you write this then?

> I don't understand why KLEE is not defined when BUG is. I think that's the problem.

What are you referring to? In the spec for `vectors_klee_bug.x86_64`, `BUG` is set to `1` and `KLEE` is defined.

**Comment by ccadar** [comment]
I wrote the benchmark, but you wrote the spec file.

OK, the `null` is defined, seems like a confusing choice :)

**Comment by ccadar** [comment]
If `KLEE` is defined, than I believe the spec is correct, those lines should be reachable.

**Comment by delcypher** [comment]
`KLEE: null` is equivalent to passing `-DKLEE` to the compiler. It means the macro is defined but does not give it a value. If a macro is listed in `defines` that means it is defined. If a macro is **not** listed there it is **not defined**.

**Comment by ccadar** [comment]
OK, we agree on that.  As I said, I think those lines are reachable.  Try running the native version: I believe all asserts should pass.

**Comment by delcypher** [comment]
> If KLEE is defined, than I believe the spec is correct, those lines should be reachable.

By "reachable" I mean they can be reached and fail. Counter examples are supposed to be reachable failing asserts.

Our tool disagrees it only generates two paths. An assertion failure

```
KLEE: ERROR: /home/user/fp-bench/benchmarks/c/imperial/gsl/benchmarks/vectors/vector_example.c:56: ASSERTION FAIL: min_x == min_y
```

and the other path completes execution without failure

This suggests to me that if the symbolic data is NaN then then we will fail at the first assert and therefore can't reach and fail at the others.

**Comment by ccadar** [comment]
OK, I understand now.  Yes, you are right, so the fix is just to remove those last 2 counterexamples.

**Comment by delcypher** [comment]
@ccadar That's what I think we should do but I want to get approval from the benchmark author. I've checked @afd wrote the spec here. Ally do you agree with out assessment here?

**Comment by ccadar** [comment]
`git log` shows that you did, am I reading this incorrectly?...

**Comment by delcypher** [comment]
@ccadar You need to look at the old repo (the one containing our original commits for this repo). The entire history got squashed when we did benchmark exchange.

**Comment by ccadar** [comment]
I see, I forgot about our old repo.
