### ISSUE TITLE
`statistics_klee_bug.x86_64.bc` may have unreachable asserts

### ISSUE THREAD

**Issue by delcypher** [delcypher/fp-benchmarks-imperial#15]
The `statistics_klee_bug.x86_64.bc`benchmark declares several counter example locations in its spec. However when I run our tool on it some of those are not covered. Our exploration is not exhaustive unfortunately so unlike #13 I'm less certain if those asserts are reachable.

When later analysing a run of our tool I get the following warning.

```
WARNING:MainThread: MATCH SPEC for task no_assert_fail but with warnings:
/home/user/build_O2/benchmarks/c/imperial/gsl/benchmarks/statistics_klee_bug.x86_64.bc (/home/imperial/experiments/imperial/tool_exchange/0/wd/workdir-55/klee-wd)
Observed counter examples do not cover all listed for this task in spec. The following locations were not covered:
{'stat.c': {45, 48, 49, 50, 51, 52}}
```

We observe assertion failures on lines 44, 46 and 47.

I worry that some of the counter examples given are actually not reachable. @ccadar could you look into this?

**Comment by ccadar** [comment]
OK, so this is similar to #14 , only the first counterexample should be kept in the spec.

**Comment by delcypher** [comment]
@ccadar Just to be clear our tool does **not do exhaustive exploration** on this benchmark so I can't be sure about the reachability of the failing asserts
. I also took a look at the old repo. @afd actually wrote the spec here.

**Comment by delcypher** [comment]
I'm not going to make the change for now given that the tool exploration was not exhaustive. I do not trust my intuition.

**Comment by delcypher** [comment]
By construction `assert(largest >= 10.0);` on line 45 cannot fail. The NaN case is handled by the previous assert and the data array contains the concrete values `18.3` and `12.6` which will always be larger than `10.0` so we can eliminate this one.

This assumes `gsl_stats_max()` is correctly implemented.

**Comment by delcypher** [comment]
Similarly `assert(smallest <= 20.0);` on line 48 cannot fail. The NaN case is already handled by previous asserts. By construction the smallest value value will always be less than `20.0`. The concrete values are all less than `20.0` and for the symbolic value it will either be the smallest value or it will not but this does not the affect the outcome of this assertion.

This assumes `gsl_stats_min()` is correctly implemented.

**Comment by delcypher** [comment]
The `assert(mean >= 10.0)` (line 49) and `assert(mean <= 20.0)` (line 50) cannot fail. By this point the execution it is guaranteed that all members of `data` are in the range `[10.0, 20.0]`. If `gsl_stats_mean()` is correctly implemented this implies that the mean must be within this range too.

**Comment by delcypher** [comment]
The `assert(variance >= 0.0)` (line 51) cannot fail assuming the `gsl_stats_variance()` function is correctly implemented. The NaN case is already handled by previous asserts.

**Comment by delcypher** [comment]
The `assert(variance <= 50.0) (line 52) cannot fail assuming the gsl_stats_variance() function is correctly implemented. The NaN case is already handled by previous asserts.

According to the Popoviciu inequality on variance the upper bound for the variance is (M - m)^2 /4 where M and m are the upper and lower bounds respectively of the values used to compute the mean. In this case that gives an upper bound of `25.0` which is a tigher bound than that enforced by the assert.

**Comment by delcypher** [comment]
This is now fixed by

0ff99070598840fb7ea9787a793aae88ef78def7
1e3a5dda7a01ad3e8d822ee6f86c7d827cf70254
0763d8c344ee6c13c51bf91140ec9c4baacb9f1c
56212717291c5f104b1fa8107d37e89ac9b5db1e
694c6c3fbd0216189812ac80e918b0892dd51292
