### ISSUE TITLE
interval_klee_bug.x86_64.bc may have unreachable asserts.

### ISSUE THREAD

**Issue by delcypher** [delcypher/fp-benchmarks-imperial#16]
The `interval_klee_bug.x86_64.bc` benchmark declares several counter example locations in its spec. However when I run our tool on it some of those are not covered. Our exploration is not exhaustive unfortunately so unlike #13 I'm less certain if those asserts are reachable.

```
WARNING:MainThread: MATCH SPEC for task no_assert_fail but with warnings:
/home/user/build_O2/benchmarks/c/imperial/synthetic/interval_klee_bug.x86_64.bc (/home/imperial/experiments/imperial/tool_exchange/0/wd/workdir-60/klee-wd)
Observed counter examples do not cover all listed for this task in spec. The following locations were not covered:
{'interval.c': {104}}
```

We observe failures on line 99. @afd are you sure line 104 is reachable? Could you look into this?

**Comment by delcypher** [comment]
I'm not going to make the change for now given that the tool exploration was not exhaustive. I do not trust my intuition.

**Comment by ccadar** [comment]
I think that's indeed the case though.  Have you also checked with Ally?

**Comment by delcypher** [comment]
@ccadar I've asked @afd to look. Given that I'm currently writing a presentation on fuzzing I'm going to try and fuzz it now.

**Comment by delcypher** [comment]
LibFuzzer confirms that this assert (on line 104) is reachable (example value `2755254.000000 (0x1.5055bp+21)`).

Unfortunately it has also confirmed that the `klee_no_bug` variant actually has bugs in it.

**Comment by delcypher** [comment]
Something is wrong with my LibFuzzer setup I can't confirm any of the bugs its finding.

**Comment by delcypher** [comment]
Oh no something very wrong is going on here. If I build the benchmark with `-O2` I can get the `klee_no_bug` benchmark to fail during fuzzing but when I do a -O0 build it doesn't...

**Comment by delcypher** [comment]
I think this is a bug in Clang. I'll report it once I'm able to reduce it a bit.

Anyway LibFuzzer found an input that I can reproduce failing the assert on line `104`. The input was

* -63652.164062 (-0x1.f14854p+15)

So we can close this
