### ISSUE TITLE
synthetic/count_non_klee_bug.x86_64 expects assertion on wrong line

### ISSUE THREAD

**Issue by erzett** [delcypher/fp-benchmarks-imperial#8]
This variant expects an assertion failure on line 79, but the corresponding assertion is on line 81.

**Comment by delcypher** [comment]
This is not part of the issta_2017 category so it is not supposed to be executed by either team. However I will fix this.

**Comment by delcypher** [comment]
Fixed in 30ea85c3c4961a2e2f8a39a9dead8dc90e9d042c
